// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPeakReadingTimeForDeviceDay = `-- name: GetPeakReadingTimeForDeviceDay :one
SELECT ts FROM telemetry
WHERE device_id = $1 AND ts >= $2 AND ts < $3 AND power_kw = $4
ORDER BY ts LIMIT 1
`

type GetPeakReadingTimeForDeviceDayParams struct {
	DeviceID string
	Ts       pgtype.Timestamptz
	Ts_2     pgtype.Timestamptz
	PowerKw  float64
}

// Continuous aggregates can't express argmax, so the peak reading's time
// of day is resolved via a narrow indexed point lookup instead of a scan.
func (q *Queries) GetPeakReadingTimeForDeviceDay(ctx context.Context, arg GetPeakReadingTimeForDeviceDayParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getPeakReadingTimeForDeviceDay,
		arg.DeviceID,
		arg.Ts,
		arg.Ts_2,
		arg.PowerKw,
	)
	var ts pgtype.Timestamptz
	err := row.Scan(&ts)
	return ts, err
}

const getRawEnergyReadingsForDeviceDay = `-- name: GetRawEnergyReadingsForDeviceDay :many
SELECT ts, energy_kwh_total FROM telemetry
WHERE device_id = $1 AND ts >= $2 AND ts < $3
ORDER BY ts
`

type GetRawEnergyReadingsForDeviceDayParams struct {
	DeviceID string
	Ts       pgtype.Timestamptz
	Ts_2     pgtype.Timestamptz
}

type GetRawEnergyReadingsForDeviceDayRow struct {
	Ts             pgtype.Timestamptz
	EnergyKwhTotal float64
}

// Reset-day fallback: ordered readings for one device on one day. The
// registry computes true daily energy as sum(max(0, e[i] - e[i-1])) over
// consecutive readings — this correctly captures both the pre-reset and
// post-reset segments' real generation while ignoring the reset's negative
// delta, without needing to know exactly when in the day the reset
// occurred.
func (q *Queries) GetRawEnergyReadingsForDeviceDay(ctx context.Context, arg GetRawEnergyReadingsForDeviceDayParams) ([]GetRawEnergyReadingsForDeviceDayRow, error) {
	rows, err := q.db.Query(ctx, getRawEnergyReadingsForDeviceDay, arg.DeviceID, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRawEnergyReadingsForDeviceDayRow
	for rows.Next() {
		var i GetRawEnergyReadingsForDeviceDayRow
		if err := rows.Scan(&i.Ts, &i.EnergyKwhTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetDailyRollup = `-- name: ListFleetDailyRollup :many
SELECT device_id, site_id, day, peak_power_kw, energy_start_kwh, energy_end_kwh, reading_count, backfilled_count, has_reset
FROM telemetry_daily
WHERE day >= $1 AND day <= $2
  AND (
    $3::text IS NULL
    OR site_id IN (SELECT site_id FROM sites WHERE cohort_id = $3)
  )
ORDER BY day, site_id, device_id
`

type ListFleetDailyRollupParams struct {
	Day      pgtype.Timestamptz
	Day_2    pgtype.Timestamptz
	CohortID pgtype.Text
}

// Same shape as ListSiteDailyRollup but fleet-wide, optionally filtered to
// a cohort. Used by fleet energy/trends/benchmark/anomaly registry logic.
func (q *Queries) ListFleetDailyRollup(ctx context.Context, arg ListFleetDailyRollupParams) ([]TelemetryDaily, error) {
	rows, err := q.db.Query(ctx, listFleetDailyRollup, arg.Day, arg.Day_2, arg.CohortID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelemetryDaily
	for rows.Next() {
		var i TelemetryDaily
		if err := rows.Scan(
			&i.DeviceID,
			&i.SiteID,
			&i.Day,
			&i.PeakPowerKw,
			&i.EnergyStartKwh,
			&i.EnergyEndKwh,
			&i.ReadingCount,
			&i.BackfilledCount,
			&i.HasReset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteDailyRollup = `-- name: ListSiteDailyRollup :many
SELECT device_id, day, peak_power_kw, energy_start_kwh, energy_end_kwh, reading_count, backfilled_count, has_reset
FROM telemetry_daily
WHERE site_id = $1 AND day >= $2 AND day <= $3
ORDER BY day, device_id
`

type ListSiteDailyRollupParams struct {
	SiteID string
	Day    pgtype.Timestamptz
	Day_2  pgtype.Timestamptz
}

type ListSiteDailyRollupRow struct {
	DeviceID        string
	Day             pgtype.Timestamptz
	PeakPowerKw     pgtype.Float8
	EnergyStartKwh  pgtype.Float8
	EnergyEndKwh    pgtype.Float8
	ReadingCount    int64
	BackfilledCount int64
	HasReset        bool
}

// Per-device-per-day rows for one site, from the telemetry_daily continuous
// aggregate. The registry layer sums across a site's devices per day (a
// site can have more than one device) and falls back to
// GetRawEnergyReadingsForDeviceDay for any device-day where has_reset is
// true, rather than trusting energy_end_kwh - energy_start_kwh blindly
// across a counter reset.
func (q *Queries) ListSiteDailyRollup(ctx context.Context, arg ListSiteDailyRollupParams) ([]ListSiteDailyRollupRow, error) {
	rows, err := q.db.Query(ctx, listSiteDailyRollup, arg.SiteID, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSiteDailyRollupRow
	for rows.Next() {
		var i ListSiteDailyRollupRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.Day,
			&i.PeakPowerKw,
			&i.EnergyStartKwh,
			&i.EnergyEndKwh,
			&i.ReadingCount,
			&i.BackfilledCount,
			&i.HasReset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitesForAnalytics = `-- name: ListSitesForAnalytics :many
SELECT site_id, name, timezone, system_size_kw, inverter_make_model, cohort_id, created_at
FROM sites
ORDER BY site_id
`

type ListSitesForAnalyticsRow struct {
	SiteID            string
	Name              pgtype.Text
	Timezone          string
	SystemSizeKw      pgtype.Numeric
	InverterMakeModel pgtype.Text
	CohortID          pgtype.Text
	CreatedAt         pgtype.Timestamptz
}

// Unpaginated site metadata used only as an internal join for
// benchmarking/trends/comparisons (system size, inverter model, cohort).
// Not itself an API list endpoint a client paginates — the user-facing
// pagination is on the computed segments/periods, which stay small and
// bounded regardless of fleet size at the scale this stack targets today.
func (q *Queries) ListSitesForAnalytics(ctx context.Context) ([]ListSitesForAnalyticsRow, error) {
	rows, err := q.db.Query(ctx, listSitesForAnalytics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSitesForAnalyticsRow
	for rows.Next() {
		var i ListSitesForAnalyticsRow
		if err := rows.Scan(
			&i.SiteID,
			&i.Name,
			&i.Timezone,
			&i.SystemSizeKw,
			&i.InverterMakeModel,
			&i.CohortID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
