// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listUserActionAuditLog = `-- name: ListUserActionAuditLog :many
SELECT
    l.id, l.actor_user_id, u.email AS actor_email, l.action, l.target_type, l.target_id, l.metadata, l.created_at
FROM user_action_audit_log l
LEFT JOIN users u ON u.id = l.actor_user_id
WHERE
    ($1::bigint IS NULL OR l.actor_user_id = $1)
    AND ($2::text IS NULL OR l.action = $2)
    AND ($3::text IS NULL OR l.target_type = $3)
    AND ($4::text IS NULL OR l.target_id = $4)
    AND ($5::timestamptz IS NULL OR l.created_at >= $5)
    AND ($6::timestamptz IS NULL OR l.created_at <= $6)
    AND (
        $7::timestamptz IS NULL
        OR (l.created_at, l.id) < ($7::timestamptz, $8::bigint)
    )
ORDER BY l.created_at DESC, l.id DESC
LIMIT $9
`

type ListUserActionAuditLogParams struct {
	ActorUserID     pgtype.Int8
	Action          pgtype.Text
	TargetType      pgtype.Text
	TargetID        pgtype.Text
	FromTs          pgtype.Timestamptz
	ToTs            pgtype.Timestamptz
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.Int8
	PageLimit       int32
}

type ListUserActionAuditLogRow struct {
	ID          int64
	ActorUserID pgtype.Int8
	ActorEmail  pgtype.Text
	Action      string
	TargetType  pgtype.Text
	TargetID    pgtype.Text
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
}

// The Phase 3 catch-up on migration 0002's own deferred TODO ("a
// browsing/reporting UI on this table is Phase 3"). Keyset-paginated on
// (created_at, id); every filter is optional (NULL = don't filter on it).
func (q *Queries) ListUserActionAuditLog(ctx context.Context, arg ListUserActionAuditLogParams) ([]ListUserActionAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listUserActionAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.FromTs,
		arg.ToTs,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserActionAuditLogRow
	for rows.Next() {
		var i ListUserActionAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
