// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cloud_import.sql

package db

import (
	"context"
)

const createCloudImportToken = `-- name: CreateCloudImportToken :one
INSERT INTO cloud_import_tokens (device_id, token_hash) VALUES ($1, $2) RETURNING id, device_id, token_hash, created_at, last_used_at, revoked_at
`

type CreateCloudImportTokenParams struct {
	DeviceID  string
	TokenHash string
}

func (q *Queries) CreateCloudImportToken(ctx context.Context, arg CreateCloudImportTokenParams) (CloudImportToken, error) {
	row := q.db.QueryRow(ctx, createCloudImportToken, arg.DeviceID, arg.TokenHash)
	var i CloudImportToken
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveCloudImportTokensForDevice = `-- name: ListActiveCloudImportTokensForDevice :many
SELECT id, device_id, token_hash, created_at, last_used_at, revoked_at FROM cloud_import_tokens WHERE device_id = $1 AND revoked_at IS NULL
`

// Bounded to one device's own tokens (there's realistically at most one
// active, occasionally two mid-rotation) — verified by hash comparison
// in Go, same pattern as invites/password-reset tokens, since a token
// isn't looked up by its plaintext value.
func (q *Queries) ListActiveCloudImportTokensForDevice(ctx context.Context, deviceID string) ([]CloudImportToken, error) {
	rows, err := q.db.Query(ctx, listActiveCloudImportTokensForDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CloudImportToken
	for rows.Next() {
		var i CloudImportToken
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCloudImportTokenUsed = `-- name: MarkCloudImportTokenUsed :exec
UPDATE cloud_import_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) MarkCloudImportTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markCloudImportTokenUsed, id)
	return err
}

const revokeCloudImportTokensForDevice = `-- name: RevokeCloudImportTokensForDevice :exec
UPDATE cloud_import_tokens SET revoked_at = now() WHERE device_id = $1 AND revoked_at IS NULL
`

// Issuing a new token revokes any previous one for the same device — one
// active credential at a time, same model as device secret rotation.
func (q *Queries) RevokeCloudImportTokensForDevice(ctx context.Context, deviceID string) error {
	_, err := q.db.Exec(ctx, revokeCloudImportTokensForDevice, deviceID)
	return err
}
