// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDevices = `-- name: CountDevices :one
SELECT count(*)::bigint FROM devices
`

func (q *Queries) CountDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDevices)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOnlineDevices = `-- name: CountOnlineDevices :one
SELECT count(*)::bigint FROM devices
WHERE revoked_at IS NULL AND last_contact_at > $1::timestamptz
`

// cutoff is computed in Go from ONLINE_THRESHOLD_MINUTES, never a SQL
// literal, so the threshold is configurable without a query change.
// Filters on last_contact_at (reachability), not last_seen_at (reading
// freshness) — see internal/registry's two-signal online/data_gap model.
func (q *Queries) CountOnlineDevices(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countOnlineDevices, cutoff)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (device_id, site_id, secret_hash, install_notes)
VALUES ($1, $2, $3, $4)
RETURNING device_id, site_id, secret_hash, revoked_at, last_seen_at, created_at, secret_last_rotated_at, install_notes, last_contact_at
`

type CreateDeviceParams struct {
	DeviceID     string
	SiteID       pgtype.Text
	SecretHash   string
	InstallNotes pgtype.Text
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.DeviceID,
		arg.SiteID,
		arg.SecretHash,
		arg.InstallNotes,
	)
	var i Device
	err := row.Scan(
		&i.DeviceID,
		&i.SiteID,
		&i.SecretHash,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretLastRotatedAt,
		&i.InstallNotes,
		&i.LastContactAt,
	)
	return i, err
}

const currentFleetGeneration = `-- name: CurrentFleetGeneration :one
SELECT coalesce(sum(latest.power_kw), 0)::double precision AS current_power_kw
FROM devices d
JOIN LATERAL (
    SELECT power_kw FROM telemetry t WHERE t.device_id = d.device_id ORDER BY t.ts DESC LIMIT 1
) latest ON true
WHERE d.revoked_at IS NULL AND d.last_contact_at > $1::timestamptz
`

// Sum of the most recent power_kw reading per online (not revoked,
// contacted within the online threshold) device — a live "how much
// power right now" figure, distinct from any cumulative/historical
// energy total elsewhere on this platform. A LATERAL join per device,
// not a rollup — deliberately live, not pre-aggregated.
func (q *Queries) CurrentFleetGeneration(ctx context.Context, onlineCutoff pgtype.Timestamptz) (float64, error) {
	row := q.db.QueryRow(ctx, currentFleetGeneration, onlineCutoff)
	var current_power_kw float64
	err := row.Scan(&current_power_kw)
	return current_power_kw, err
}

const getDevice = `-- name: GetDevice :one
SELECT device_id, site_id, secret_hash, revoked_at, last_seen_at, created_at, secret_last_rotated_at, install_notes, last_contact_at FROM devices WHERE device_id = $1
`

func (q *Queries) GetDevice(ctx context.Context, deviceID string) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, deviceID)
	var i Device
	err := row.Scan(
		&i.DeviceID,
		&i.SiteID,
		&i.SecretHash,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretLastRotatedAt,
		&i.InstallNotes,
		&i.LastContactAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT device_id, site_id, secret_hash, revoked_at, last_seen_at, created_at, secret_last_rotated_at, install_notes, last_contact_at FROM devices
WHERE ($1::text IS NULL OR site_id = $1)
  AND (
    $2::timestamptz IS NULL
    OR (created_at, device_id) < ($2::timestamptz, $3::text)
  )
ORDER BY created_at DESC, device_id DESC
LIMIT $4
`

type ListDevicesParams struct {
	SiteFilter      pgtype.Text
	CursorCreatedAt pgtype.Timestamptz
	CursorDeviceID  pgtype.Text
	PageLimit       int32
}

// site_filter NULL means "all devices" (operator, no ?site_id= filter).
func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices,
		arg.SiteFilter,
		arg.CursorCreatedAt,
		arg.CursorDeviceID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.DeviceID,
			&i.SiteID,
			&i.SecretHash,
			&i.RevokedAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.SecretLastRotatedAt,
			&i.InstallNotes,
			&i.LastContactAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFaultReadings = `-- name: ListRecentFaultReadings :many
SELECT DISTINCT ON (device_id) device_id, site_id, ts, status
FROM telemetry
WHERE status = 'fault' AND ts > $1::timestamptz
ORDER BY device_id, ts DESC
`

type ListRecentFaultReadingsRow struct {
	DeviceID string
	SiteID   string
	Ts       pgtype.Timestamptz
	Status   ReadingStatus
}

// Latest reading per device that reported status='fault' within the
// window, one row per device (DISTINCT ON), for the Alerts page. A raw
// scan over recent telemetry, not a rollup — telemetry_daily doesn't
// track status, and this is bounded to a short recent window, not the
// full history CLAUDE.md's "hit roll-ups" rule is about.
func (q *Queries) ListRecentFaultReadings(ctx context.Context, since pgtype.Timestamptz) ([]ListRecentFaultReadingsRow, error) {
	rows, err := q.db.Query(ctx, listRecentFaultReadings, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentFaultReadingsRow
	for rows.Next() {
		var i ListRecentFaultReadingsRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.SiteID,
			&i.Ts,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentlyRevokedDevices = `-- name: ListRecentlyRevokedDevices :many
SELECT device_id, site_id, secret_hash, revoked_at, last_seen_at, created_at, secret_last_rotated_at, install_notes, last_contact_at FROM devices
WHERE revoked_at IS NOT NULL AND revoked_at > $1::timestamptz
ORDER BY revoked_at DESC
`

// Feeds the Alerts page — a revocation is a real, timestamped event
// worth surfacing there, same as an offline/fault condition.
func (q *Queries) ListRecentlyRevokedDevices(ctx context.Context, since pgtype.Timestamptz) ([]Device, error) {
	rows, err := q.db.Query(ctx, listRecentlyRevokedDevices, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.DeviceID,
			&i.SiteID,
			&i.SecretHash,
			&i.RevokedAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.SecretLastRotatedAt,
			&i.InstallNotes,
			&i.LastContactAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :one
UPDATE devices SET revoked_at = now() WHERE device_id = $1 RETURNING device_id, site_id, secret_hash, revoked_at, last_seen_at, created_at, secret_last_rotated_at, install_notes, last_contact_at
`

func (q *Queries) RevokeDevice(ctx context.Context, deviceID string) (Device, error) {
	row := q.db.QueryRow(ctx, revokeDevice, deviceID)
	var i Device
	err := row.Scan(
		&i.DeviceID,
		&i.SiteID,
		&i.SecretHash,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretLastRotatedAt,
		&i.InstallNotes,
		&i.LastContactAt,
	)
	return i, err
}

const rotateDeviceSecret = `-- name: RotateDeviceSecret :one
UPDATE devices SET secret_hash = $2, secret_last_rotated_at = now() WHERE device_id = $1 RETURNING device_id, site_id, secret_hash, revoked_at, last_seen_at, created_at, secret_last_rotated_at, install_notes, last_contact_at
`

type RotateDeviceSecretParams struct {
	DeviceID   string
	SecretHash string
}

func (q *Queries) RotateDeviceSecret(ctx context.Context, arg RotateDeviceSecretParams) (Device, error) {
	row := q.db.QueryRow(ctx, rotateDeviceSecret, arg.DeviceID, arg.SecretHash)
	var i Device
	err := row.Scan(
		&i.DeviceID,
		&i.SiteID,
		&i.SecretHash,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretLastRotatedAt,
		&i.InstallNotes,
		&i.LastContactAt,
	)
	return i, err
}
