// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDevices = `-- name: CountDevices :one
SELECT count(*)::bigint FROM devices
`

func (q *Queries) CountDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDevices)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOnlineDevices = `-- name: CountOnlineDevices :one
SELECT count(*)::bigint FROM devices
WHERE revoked_at IS NULL AND last_contact_at > $1::timestamptz
`

// cutoff is computed in Go from ONLINE_THRESHOLD_MINUTES, never a SQL
// literal, so the threshold is configurable without a query change.
// Filters on last_contact_at (reachability), not last_seen_at (reading
// freshness) — see internal/registry's two-signal online/data_gap model.
func (q *Queries) CountOnlineDevices(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countOnlineDevices, cutoff)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (device_id, site_id, secret_hash, install_notes)
VALUES ($1, $2, $3, $4)
RETURNING device_id, site_id, secret_hash, revoked_at, last_seen_at, created_at, secret_last_rotated_at, install_notes, last_contact_at
`

type CreateDeviceParams struct {
	DeviceID     string
	SiteID       pgtype.Text
	SecretHash   string
	InstallNotes pgtype.Text
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.DeviceID,
		arg.SiteID,
		arg.SecretHash,
		arg.InstallNotes,
	)
	var i Device
	err := row.Scan(
		&i.DeviceID,
		&i.SiteID,
		&i.SecretHash,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretLastRotatedAt,
		&i.InstallNotes,
		&i.LastContactAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT device_id, site_id, secret_hash, revoked_at, last_seen_at, created_at, secret_last_rotated_at, install_notes, last_contact_at FROM devices WHERE device_id = $1
`

func (q *Queries) GetDevice(ctx context.Context, deviceID string) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, deviceID)
	var i Device
	err := row.Scan(
		&i.DeviceID,
		&i.SiteID,
		&i.SecretHash,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretLastRotatedAt,
		&i.InstallNotes,
		&i.LastContactAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT device_id, site_id, secret_hash, revoked_at, last_seen_at, created_at, secret_last_rotated_at, install_notes, last_contact_at FROM devices
WHERE ($1::text IS NULL OR site_id = $1)
  AND (
    $2::timestamptz IS NULL
    OR (created_at, device_id) < ($2::timestamptz, $3::text)
  )
ORDER BY created_at DESC, device_id DESC
LIMIT $4
`

type ListDevicesParams struct {
	SiteFilter      pgtype.Text
	CursorCreatedAt pgtype.Timestamptz
	CursorDeviceID  pgtype.Text
	PageLimit       int32
}

// site_filter NULL means "all devices" (operator, no ?site_id= filter).
func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices,
		arg.SiteFilter,
		arg.CursorCreatedAt,
		arg.CursorDeviceID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.DeviceID,
			&i.SiteID,
			&i.SecretHash,
			&i.RevokedAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.SecretLastRotatedAt,
			&i.InstallNotes,
			&i.LastContactAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :one
UPDATE devices SET revoked_at = now() WHERE device_id = $1 RETURNING device_id, site_id, secret_hash, revoked_at, last_seen_at, created_at, secret_last_rotated_at, install_notes, last_contact_at
`

func (q *Queries) RevokeDevice(ctx context.Context, deviceID string) (Device, error) {
	row := q.db.QueryRow(ctx, revokeDevice, deviceID)
	var i Device
	err := row.Scan(
		&i.DeviceID,
		&i.SiteID,
		&i.SecretHash,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretLastRotatedAt,
		&i.InstallNotes,
		&i.LastContactAt,
	)
	return i, err
}

const rotateDeviceSecret = `-- name: RotateDeviceSecret :one
UPDATE devices SET secret_hash = $2, secret_last_rotated_at = now() WHERE device_id = $1 RETURNING device_id, site_id, secret_hash, revoked_at, last_seen_at, created_at, secret_last_rotated_at, install_notes, last_contact_at
`

type RotateDeviceSecretParams struct {
	DeviceID   string
	SecretHash string
}

func (q *Queries) RotateDeviceSecret(ctx context.Context, arg RotateDeviceSecretParams) (Device, error) {
	row := q.db.QueryRow(ctx, rotateDeviceSecret, arg.DeviceID, arg.SecretHash)
	var i Device
	err := row.Scan(
		&i.DeviceID,
		&i.SiteID,
		&i.SecretHash,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.SecretLastRotatedAt,
		&i.InstallNotes,
		&i.LastContactAt,
	)
	return i, err
}
