// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmissionFactor = `-- name: CreateEmissionFactor :one
INSERT INTO grid_emission_factor (kg_co2_per_kwh, country, source, effective_from, created_by_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, kg_co2_per_kwh, country, source, effective_from, created_at, created_by_user_id
`

type CreateEmissionFactorParams struct {
	KgCo2PerKwh     pgtype.Numeric
	Country         string
	Source          string
	EffectiveFrom   pgtype.Timestamptz
	CreatedByUserID pgtype.Int8
}

// Append-only — never UPDATE. Past reports must stay reproducible even if
// the official factor changes later.
func (q *Queries) CreateEmissionFactor(ctx context.Context, arg CreateEmissionFactorParams) (GridEmissionFactor, error) {
	row := q.db.QueryRow(ctx, createEmissionFactor,
		arg.KgCo2PerKwh,
		arg.Country,
		arg.Source,
		arg.EffectiveFrom,
		arg.CreatedByUserID,
	)
	var i GridEmissionFactor
	err := row.Scan(
		&i.ID,
		&i.KgCo2PerKwh,
		&i.Country,
		&i.Source,
		&i.EffectiveFrom,
		&i.CreatedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const getCurrentEmissionFactor = `-- name: GetCurrentEmissionFactor :one
SELECT id, kg_co2_per_kwh, country, source, effective_from, created_at, created_by_user_id FROM grid_emission_factor WHERE country = $1 ORDER BY effective_from DESC LIMIT 1
`

// The most recently effective factor for a country. Returns pgx.ErrNoRows
// until an operator has explicitly set one — callers must turn that into a
// 409, never a fabricated default.
func (q *Queries) GetCurrentEmissionFactor(ctx context.Context, country string) (GridEmissionFactor, error) {
	row := q.db.QueryRow(ctx, getCurrentEmissionFactor, country)
	var i GridEmissionFactor
	err := row.Scan(
		&i.ID,
		&i.KgCo2PerKwh,
		&i.Country,
		&i.Source,
		&i.EffectiveFrom,
		&i.CreatedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const listAllEmissionFactorsForCountry = `-- name: ListAllEmissionFactorsForCountry :many
SELECT id, kg_co2_per_kwh, country, source, effective_from, created_at, created_by_user_id FROM grid_emission_factor WHERE country = $1 ORDER BY effective_from ASC
`

// Unbounded on purpose, unlike ListEmissionFactorHistory above — this
// feeds per-period historical lookup (Emissions.factorAsOf), which needs
// every revision ever set for the country, not a capped "recent N" list.
// Safe to leave unbounded: this table only grows via a rare admin action
// (Emissions.Set), never per-reading, so it stays tiny for the table's
// entire lifetime — nothing like telemetry's scale.
func (q *Queries) ListAllEmissionFactorsForCountry(ctx context.Context, country string) ([]GridEmissionFactor, error) {
	rows, err := q.db.Query(ctx, listAllEmissionFactorsForCountry, country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GridEmissionFactor
	for rows.Next() {
		var i GridEmissionFactor
		if err := rows.Scan(
			&i.ID,
			&i.KgCo2PerKwh,
			&i.Country,
			&i.Source,
			&i.EffectiveFrom,
			&i.CreatedAt,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmissionFactorHistory = `-- name: ListEmissionFactorHistory :many
SELECT id, kg_co2_per_kwh, country, source, effective_from, created_at, created_by_user_id FROM grid_emission_factor WHERE country = $1 ORDER BY effective_from DESC LIMIT $2
`

type ListEmissionFactorHistoryParams struct {
	Country string
	Limit   int32
}

func (q *Queries) ListEmissionFactorHistory(ctx context.Context, arg ListEmissionFactorHistoryParams) ([]GridEmissionFactor, error) {
	rows, err := q.db.Query(ctx, listEmissionFactorHistory, arg.Country, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GridEmissionFactor
	for rows.Next() {
		var i GridEmissionFactor
		if err := rows.Scan(
			&i.ID,
			&i.KgCo2PerKwh,
			&i.Country,
			&i.Source,
			&i.EffectiveFrom,
			&i.CreatedAt,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
