// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExportJob = `-- name: CreateExportJob :one
INSERT INTO export_jobs (requested_by_user_id, job_type, site_id)
VALUES ($1, $2, $3)
RETURNING id, requested_by_user_id, job_type, site_id, status, result_key, error, created_at, completed_at
`

type CreateExportJobParams struct {
	RequestedByUserID int64
	JobType           ExportJobType
	SiteID            pgtype.Text
}

func (q *Queries) CreateExportJob(ctx context.Context, arg CreateExportJobParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, createExportJob, arg.RequestedByUserID, arg.JobType, arg.SiteID)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.RequestedByUserID,
		&i.JobType,
		&i.SiteID,
		&i.Status,
		&i.ResultKey,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getExportJob = `-- name: GetExportJob :one
SELECT id, requested_by_user_id, job_type, site_id, status, result_key, error, created_at, completed_at FROM export_jobs WHERE id = $1
`

func (q *Queries) GetExportJob(ctx context.Context, id int64) (ExportJob, error) {
	row := q.db.QueryRow(ctx, getExportJob, id)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.RequestedByUserID,
		&i.JobType,
		&i.SiteID,
		&i.Status,
		&i.ResultKey,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listExportJobsForUser = `-- name: ListExportJobsForUser :many
SELECT id, requested_by_user_id, job_type, site_id, status, result_key, error, created_at, completed_at FROM export_jobs WHERE requested_by_user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListExportJobsForUserParams struct {
	RequestedByUserID int64
	Limit             int32
}

func (q *Queries) ListExportJobsForUser(ctx context.Context, arg ListExportJobsForUserParams) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listExportJobsForUser, arg.RequestedByUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportJob
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.RequestedByUserID,
			&i.JobType,
			&i.SiteID,
			&i.Status,
			&i.ResultKey,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExportJobCompleted = `-- name: MarkExportJobCompleted :exec
UPDATE export_jobs SET status = 'completed', result_key = $2, completed_at = now() WHERE id = $1
`

type MarkExportJobCompletedParams struct {
	ID        int64
	ResultKey pgtype.Text
}

func (q *Queries) MarkExportJobCompleted(ctx context.Context, arg MarkExportJobCompletedParams) error {
	_, err := q.db.Exec(ctx, markExportJobCompleted, arg.ID, arg.ResultKey)
	return err
}

const markExportJobFailed = `-- name: MarkExportJobFailed :exec
UPDATE export_jobs SET status = 'failed', error = $2, completed_at = now() WHERE id = $1
`

type MarkExportJobFailedParams struct {
	ID    int64
	Error pgtype.Text
}

func (q *Queries) MarkExportJobFailed(ctx context.Context, arg MarkExportJobFailedParams) error {
	_, err := q.db.Exec(ctx, markExportJobFailed, arg.ID, arg.Error)
	return err
}

const markExportJobRunning = `-- name: MarkExportJobRunning :exec
UPDATE export_jobs SET status = 'running' WHERE id = $1
`

func (q *Queries) MarkExportJobRunning(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markExportJobRunning, id)
	return err
}
