// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fleet_health.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fleetHealthTotals = `-- name: FleetHealthTotals :one
WITH device_stats AS (
    SELECT
        d.device_id,
        d.created_at,
        count(t.ts) AS actual_readings
    FROM devices d
    LEFT JOIN telemetry t
        ON t.device_id = d.device_id
       AND t.ts >= $2::timestamptz
       AND t.ts <= $3::timestamptz
    GROUP BY d.device_id, d.created_at
),
expected AS (
    SELECT
        actual_readings,
        -- greatest(window_start, created_at) avoids penalizing a device for
        -- the portion of the window before it existed.
        GREATEST(
            EXTRACT(EPOCH FROM ($3::timestamptz - GREATEST($2::timestamptz, created_at)))
              / $4::float8,
            0
        ) AS expected_readings
    FROM device_stats
)
SELECT
    (SELECT count(*)::bigint FROM sites) AS total_sites,
    (SELECT count(*)::bigint FROM devices) AS total_devices,
    (SELECT count(*)::bigint FROM devices WHERE revoked_at IS NULL AND last_contact_at > $1::timestamptz) AS online_devices,
    COALESCE(SUM(actual_readings), 0)::bigint AS total_actual_readings,
    COALESCE(SUM(expected_readings), 0)::float8 AS total_expected_readings
FROM expected
`

type FleetHealthTotalsParams struct {
	OnlineCutoff            pgtype.Timestamptz
	WindowStart             pgtype.Timestamptz
	Now                     pgtype.Timestamptz
	ExpectedIntervalSeconds float64
}

type FleetHealthTotalsRow struct {
	TotalSites            int64
	TotalDevices          int64
	OnlineDevices         int64
	TotalActualReadings   int64
	TotalExpectedReadings float64
}

// Ratio-of-sums coverage (sum(actual)/sum(expected) across all devices),
// not an average of per-device percentages — avoids a brand-new device's
// tiny expected-readings denominator distorting the fleet-wide figure.
// Coverage percentage itself is computed in Go from these two sums to
// avoid a division-by-zero edge case in SQL when there are no devices yet.
func (q *Queries) FleetHealthTotals(ctx context.Context, arg FleetHealthTotalsParams) (FleetHealthTotalsRow, error) {
	row := q.db.QueryRow(ctx, fleetHealthTotals,
		arg.OnlineCutoff,
		arg.WindowStart,
		arg.Now,
		arg.ExpectedIntervalSeconds,
	)
	var i FleetHealthTotalsRow
	err := row.Scan(
		&i.TotalSites,
		&i.TotalDevices,
		&i.OnlineDevices,
		&i.TotalActualReadings,
		&i.TotalExpectedReadings,
	)
	return i, err
}

const listSiteHealth = `-- name: ListSiteHealth :many
WITH device_stats AS (
    SELECT
        d.device_id,
        d.site_id,
        d.created_at,
        d.last_seen_at,
        d.revoked_at,
        d.last_contact_at,
        count(t.ts) AS actual_readings
    FROM devices d
    LEFT JOIN telemetry t
        ON t.device_id = d.device_id
       AND t.ts >= $4::timestamptz
       AND t.ts <= $5::timestamptz
    GROUP BY d.device_id, d.site_id, d.created_at, d.last_seen_at, d.revoked_at, d.last_contact_at
),
per_device AS (
    SELECT
        device_id, site_id, last_seen_at, revoked_at, last_contact_at,
        actual_readings,
        GREATEST(
            EXTRACT(EPOCH FROM ($5::timestamptz - GREATEST($4::timestamptz, created_at)))
              / $6::float8,
            0
        ) AS expected_readings
    FROM device_stats
)
SELECT
    s.site_id,
    s.name AS site_name,
    s.created_at AS site_created_at,
    count(pd.device_id)::bigint AS total_devices,
    count(pd.device_id) FILTER (
        WHERE pd.revoked_at IS NULL AND pd.last_contact_at > $1::timestamptz
    )::bigint AS online_devices,
    COALESCE(SUM(pd.actual_readings), 0)::bigint AS actual_readings,
    COALESCE(SUM(pd.expected_readings), 0)::float8 AS expected_readings,
    MIN(pd.last_seen_at)::timestamptz AS worst_last_seen_at
FROM sites s
LEFT JOIN per_device pd ON pd.site_id = s.site_id
WHERE $2::text IS NULL OR s.site_id > $2
GROUP BY s.site_id, s.name, s.created_at
ORDER BY s.site_id
LIMIT $3
`

type ListSiteHealthParams struct {
	OnlineCutoff            pgtype.Timestamptz
	CursorSiteID            pgtype.Text
	PageLimit               int32
	WindowStart             pgtype.Timestamptz
	Now                     pgtype.Timestamptz
	ExpectedIntervalSeconds float64
}

type ListSiteHealthRow struct {
	SiteID           string
	SiteName         pgtype.Text
	SiteCreatedAt    pgtype.Timestamptz
	TotalDevices     int64
	OnlineDevices    int64
	ActualReadings   int64
	ExpectedReadings float64
	WorstLastSeenAt  pgtype.Timestamptz
}

// Per-site coverage breakdown, keyset-paginated on site_id (simple textual
// keyset — site_id is already the sites PK, so no secondary tiebreaker is
// needed the way created_at-sorted lists elsewhere need one).
func (q *Queries) ListSiteHealth(ctx context.Context, arg ListSiteHealthParams) ([]ListSiteHealthRow, error) {
	rows, err := q.db.Query(ctx, listSiteHealth,
		arg.OnlineCutoff,
		arg.CursorSiteID,
		arg.PageLimit,
		arg.WindowStart,
		arg.Now,
		arg.ExpectedIntervalSeconds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSiteHealthRow
	for rows.Next() {
		var i ListSiteHealthRow
		if err := rows.Scan(
			&i.SiteID,
			&i.SiteName,
			&i.SiteCreatedAt,
			&i.TotalDevices,
			&i.OnlineDevices,
			&i.ActualReadings,
			&i.ExpectedReadings,
			&i.WorstLastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
