// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingestion_audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIngestionAuditRow = `-- name: CreateIngestionAuditRow :one
INSERT INTO ingestion_audit_log (device_id, raw_payload) VALUES ($1, $2) RETURNING id
`

type CreateIngestionAuditRowParams struct {
	DeviceID   string
	RawPayload []byte
}

// Same "audit first, unconditionally, before any validation" discipline
// as cmd/ingestor/main.go's raw-pgx insert — used by the cloud-import
// path so a cloud-pushed reading gets the identical audit trail a real
// MQTT message does. prev_hash/entry_hash are filled in by
// trg_ingestion_audit_log_chain (migrations/0013), not here.
func (q *Queries) CreateIngestionAuditRow(ctx context.Context, arg CreateIngestionAuditRowParams) (int64, error) {
	row := q.db.QueryRow(ctx, createIngestionAuditRow, arg.DeviceID, arg.RawPayload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lastIngestionReceivedAt = `-- name: LastIngestionReceivedAt :one
SELECT max(received_at)::timestamptz AS last_received_at FROM ingestion_audit_log
`

// Most recent message the ingestor has seen, fleet-wide, regardless of
// whether it passed validation — the Dashboard's ingestion-pipeline
// status widget uses "how long ago was that" as its health signal, not
// a synthetic uptime percentage this platform has no way to compute.
func (q *Queries) LastIngestionReceivedAt(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, lastIngestionReceivedAt)
	var last_received_at pgtype.Timestamptz
	err := row.Scan(&last_received_at)
	return last_received_at, err
}

const listIngestionAuditLog = `-- name: ListIngestionAuditLog :many
SELECT
    l.id, l.device_id, d.site_id, l.raw_payload, l.received_at, l.processed, l.error
FROM ingestion_audit_log l
LEFT JOIN devices d ON d.device_id = l.device_id
WHERE
    ($1::text IS NULL OR d.site_id = $1)
    AND ($2::text IS NULL OR l.device_id = $2)
    AND ($3::boolean IS NULL OR (l.error IS NOT NULL) = $3)
    AND ($4::timestamptz IS NULL OR l.received_at >= $4)
    AND ($5::timestamptz IS NULL OR l.received_at <= $5)
    AND (
        $6::timestamptz IS NULL
        OR (l.received_at, l.id) < ($6::timestamptz, $7::bigint)
    )
ORDER BY l.received_at DESC, l.id DESC
LIMIT $8
`

type ListIngestionAuditLogParams struct {
	SiteID           pgtype.Text
	DeviceID         pgtype.Text
	ErrorsOnly       pgtype.Bool
	FromTs           pgtype.Timestamptz
	ToTs             pgtype.Timestamptz
	CursorReceivedAt pgtype.Timestamptz
	CursorID         pgtype.Int8
	PageLimit        int32
}

type ListIngestionAuditLogRow struct {
	ID         int64
	DeviceID   string
	SiteID     pgtype.Text
	RawPayload []byte
	ReceivedAt pgtype.Timestamptz
	Processed  bool
	Error      pgtype.Text
}

// The ingestor's own write-only audit trail (every message received,
// before validation — see migrations/0001_init.sql), finally given a read
// path. Kept deliberately separate from user_action_audit_log — this is
// data-quality/verification evidence, not an admin-action trail (see
// CLAUDE.md: "don't conflate the two"). Joins devices to resolve site_id
// for site-scoping (restricted users) and display, since the log itself
// only stores device_id. A device that's since been deleted still shows
// its audit rows with site_id NULL rather than disappearing.
func (q *Queries) ListIngestionAuditLog(ctx context.Context, arg ListIngestionAuditLogParams) ([]ListIngestionAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listIngestionAuditLog,
		arg.SiteID,
		arg.DeviceID,
		arg.ErrorsOnly,
		arg.FromTs,
		arg.ToTs,
		arg.CursorReceivedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIngestionAuditLogRow
	for rows.Next() {
		var i ListIngestionAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.SiteID,
			&i.RawPayload,
			&i.ReceivedAt,
			&i.Processed,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIngestionAuditError = `-- name: MarkIngestionAuditError :exec
UPDATE ingestion_audit_log SET error = $2 WHERE id = $1
`

type MarkIngestionAuditErrorParams struct {
	ID    int64
	Error pgtype.Text
}

func (q *Queries) MarkIngestionAuditError(ctx context.Context, arg MarkIngestionAuditErrorParams) error {
	_, err := q.db.Exec(ctx, markIngestionAuditError, arg.ID, arg.Error)
	return err
}

const markIngestionAuditProcessed = `-- name: MarkIngestionAuditProcessed :exec
UPDATE ingestion_audit_log SET processed = true WHERE id = $1
`

func (q *Queries) MarkIngestionAuditProcessed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markIngestionAuditProcessed, id)
	return err
}
