// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (user_id, token_hash, invited_by_user_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, invited_by_user_id, expires_at, accepted_at, created_at
`

type CreateInviteParams struct {
	UserID          int64
	TokenHash       string
	InvitedByUserID pgtype.Int8
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.UserID,
		arg.TokenHash,
		arg.InvitedByUserID,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveInvites = `-- name: ListActiveInvites :many
SELECT id, user_id, token_hash, invited_by_user_id, expires_at, accepted_at, created_at FROM invites WHERE accepted_at IS NULL AND expires_at > now()
`

// Small, TTL-bounded result set — see migrations/0007's comment on why
// token_hash isn't looked up by equality.
func (q *Queries) ListActiveInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listActiveInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.InvitedByUserID,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAccepted = `-- name: MarkInviteAccepted :exec
UPDATE invites SET accepted_at = now() WHERE id = $1
`

func (q *Queries) MarkInviteAccepted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markInviteAccepted, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
