// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ExportJobStatus string

const (
	ExportJobStatusPending   ExportJobStatus = "pending"
	ExportJobStatusRunning   ExportJobStatus = "running"
	ExportJobStatusCompleted ExportJobStatus = "completed"
	ExportJobStatusFailed    ExportJobStatus = "failed"
)

func (e *ExportJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExportJobStatus(s)
	case string:
		*e = ExportJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExportJobStatus: %T", src)
	}
	return nil
}

type NullExportJobStatus struct {
	ExportJobStatus ExportJobStatus
	Valid           bool // Valid is true if ExportJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExportJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExportJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExportJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExportJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExportJobStatus), nil
}

type ExportJobType string

const (
	ExportJobTypeSiteTelemetryCsv ExportJobType = "site_telemetry_csv"
	ExportJobTypeSiteSummaryCsv   ExportJobType = "site_summary_csv"
	ExportJobTypeFleetSummaryCsv  ExportJobType = "fleet_summary_csv"
)

func (e *ExportJobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExportJobType(s)
	case string:
		*e = ExportJobType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExportJobType: %T", src)
	}
	return nil
}

type NullExportJobType struct {
	ExportJobType ExportJobType
	Valid         bool // Valid is true if ExportJobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExportJobType) Scan(value interface{}) error {
	if value == nil {
		ns.ExportJobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExportJobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExportJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExportJobType), nil
}

type ProvenanceType string

const (
	ProvenanceTypeMetered    ProvenanceType = "metered"
	ProvenanceTypeEstimated  ProvenanceType = "estimated"
	ProvenanceTypeBackfilled ProvenanceType = "backfilled"
)

func (e *ProvenanceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProvenanceType(s)
	case string:
		*e = ProvenanceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProvenanceType: %T", src)
	}
	return nil
}

type NullProvenanceType struct {
	ProvenanceType ProvenanceType
	Valid          bool // Valid is true if ProvenanceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProvenanceType) Scan(value interface{}) error {
	if value == nil {
		ns.ProvenanceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProvenanceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProvenanceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProvenanceType), nil
}

type ReadingStatus string

const (
	ReadingStatusOk      ReadingStatus = "ok"
	ReadingStatusFault   ReadingStatus = "fault"
	ReadingStatusOffline ReadingStatus = "offline"
)

func (e *ReadingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReadingStatus(s)
	case string:
		*e = ReadingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReadingStatus: %T", src)
	}
	return nil
}

type NullReadingStatus struct {
	ReadingStatus ReadingStatus
	Valid         bool // Valid is true if ReadingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReadingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReadingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReadingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReadingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReadingStatus), nil
}

type UserRole string

const (
	UserRoleOperator   UserRole = "operator"
	UserRoleRestricted UserRole = "restricted"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Device struct {
	DeviceID            string
	SiteID              pgtype.Text
	SecretHash          string
	RevokedAt           pgtype.Timestamptz
	LastSeenAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	SecretLastRotatedAt pgtype.Timestamptz
	InstallNotes        pgtype.Text
	LastContactAt       pgtype.Timestamptz
}

type ExportJob struct {
	ID                int64
	RequestedByUserID int64
	JobType           ExportJobType
	SiteID            pgtype.Text
	Status            ExportJobStatus
	ResultKey         pgtype.Text
	Error             pgtype.Text
	CreatedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
}

type GridEmissionFactor struct {
	ID              int64
	KgCo2PerKwh     pgtype.Numeric
	Country         string
	Source          string
	EffectiveFrom   pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	CreatedByUserID pgtype.Int8
}

type IngestionAuditLog struct {
	ID         int64
	DeviceID   string
	RawPayload []byte
	ReceivedAt pgtype.Timestamptz
	Processed  bool
	Error      pgtype.Text
}

type Invite struct {
	ID              int64
	UserID          int64
	TokenHash       string
	InvitedByUserID pgtype.Int8
	ExpiresAt       pgtype.Timestamptz
	AcceptedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        int64
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Site struct {
	SiteID            string
	CohortID          pgtype.Text
	Address           pgtype.Text
	Name              pgtype.Text
	GpsLat            pgtype.Float8
	GpsLng            pgtype.Float8
	InverterMakeModel pgtype.Text
	SystemSizeKw      pgtype.Numeric
	InstallDate       pgtype.Date
	Timezone          string
	Country           string
	CreatedAt         pgtype.Timestamptz
}

type Telemetry struct {
	DeviceID       string
	SiteID         string
	Ts             pgtype.Timestamptz
	PowerKw        float64
	EnergyKwhTotal float64
	VoltageV       pgtype.Float8
	Status         ReadingStatus
	Rssi           pgtype.Int4
	Provenance     ProvenanceType
	ReceivedAt     pgtype.Timestamptz
	QualityFlags   []string
}

type TelemetryDaily struct {
	DeviceID        string
	SiteID          string
	Day             pgtype.Timestamptz
	PeakPowerKw     pgtype.Float8
	EnergyStartKwh  pgtype.Float8
	EnergyEndKwh    pgtype.Float8
	ReadingCount    int64
	BackfilledCount int64
	HasReset        bool
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Role         UserRole
	SiteID       pgtype.Text
	CreatedAt    pgtype.Timestamptz
	DisabledAt   pgtype.Timestamptz
}

type UserActionAuditLog struct {
	ID          int64
	ActorUserID pgtype.Int8
	Action      string
	TargetType  pgtype.Text
	TargetID    pgtype.Text
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
}
