// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountDevices(ctx context.Context) (int64, error)
	// cutoff is computed in Go from ONLINE_THRESHOLD_MINUTES, never a SQL
	// literal, so the threshold is configurable without a query change.
	// Filters on last_contact_at (reachability), not last_seen_at (reading
	// freshness) — see internal/registry's two-signal online/data_gap model.
	CountOnlineDevices(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	// Append-only — never UPDATE. Past reports must stay reproducible even if
	// the official factor changes later.
	CreateEmissionFactor(ctx context.Context, arg CreateEmissionFactorParams) (GridEmissionFactor, error)
	CreateExportJob(ctx context.Context, arg CreateExportJobParams) (ExportJob, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserActionAuditLog(ctx context.Context, arg CreateUserActionAuditLogParams) error
	// Ratio-of-sums coverage (sum(actual)/sum(expected) across all devices),
	// not an average of per-device percentages — avoids a brand-new device's
	// tiny expected-readings denominator distorting the fleet-wide figure.
	// Coverage percentage itself is computed in Go from these two sums to
	// avoid a division-by-zero edge case in SQL when there are no devices yet.
	FleetHealthTotals(ctx context.Context, arg FleetHealthTotalsParams) (FleetHealthTotalsRow, error)
	FleetTotals(ctx context.Context) (FleetTotalsRow, error)
	// The most recently effective factor for a country. Returns pgx.ErrNoRows
	// until an operator has explicitly set one — callers must turn that into a
	// 409, never a fabricated default.
	GetCurrentEmissionFactor(ctx context.Context, country string) (GridEmissionFactor, error)
	GetDevice(ctx context.Context, deviceID string) (Device, error)
	GetExportJob(ctx context.Context, id int64) (ExportJob, error)
	// Continuous aggregates can't express argmax, so the peak reading's time
	// of day is resolved via a narrow indexed point lookup instead of a scan.
	GetPeakReadingTimeForDeviceDay(ctx context.Context, arg GetPeakReadingTimeForDeviceDayParams) (pgtype.Timestamptz, error)
	// Reset-day fallback: ordered readings for one device on one day. The
	// registry computes true daily energy as sum(max(0, e[i] - e[i-1])) over
	// consecutive readings — this correctly captures both the pre-reset and
	// post-reset segments' real generation while ignoring the reset's negative
	// delta, without needing to know exactly when in the day the reset
	// occurred.
	GetRawEnergyReadingsForDeviceDay(ctx context.Context, arg GetRawEnergyReadingsForDeviceDayParams) ([]GetRawEnergyReadingsForDeviceDayRow, error)
	GetSite(ctx context.Context, siteID string) (Site, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	// Small, TTL-bounded result set — see migrations/0007's comment on why
	// token_hash isn't looked up by equality.
	ListActiveInvites(ctx context.Context) ([]Invite, error)
	// Same small, TTL-bounded scan-and-bcrypt-compare pattern as
	// ListActiveInvites — see migrations/0007's comment.
	ListActivePasswordResetTokens(ctx context.Context) ([]PasswordResetToken, error)
	// site_filter NULL means "all devices" (operator, no ?site_id= filter).
	ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error)
	ListEmissionFactorHistory(ctx context.Context, arg ListEmissionFactorHistoryParams) ([]GridEmissionFactor, error)
	ListExportJobsForUser(ctx context.Context, arg ListExportJobsForUserParams) ([]ExportJob, error)
	// Same shape as ListSiteDailyRollup but fleet-wide, optionally filtered to
	// a cohort. Used by fleet energy/trends/benchmark/anomaly registry logic.
	ListFleetDailyRollup(ctx context.Context, arg ListFleetDailyRollupParams) ([]TelemetryDaily, error)
	// The ingestor's own write-only audit trail (every message received,
	// before validation — see migrations/0001_init.sql), finally given a read
	// path. Kept deliberately separate from user_action_audit_log — this is
	// data-quality/verification evidence, not an admin-action trail (see
	// CLAUDE.md: "don't conflate the two"). Joins devices to resolve site_id
	// for site-scoping (restricted users) and display, since the log itself
	// only stores device_id. A device that's since been deleted still shows
	// its audit rows with site_id NULL rather than disappearing.
	ListIngestionAuditLog(ctx context.Context, arg ListIngestionAuditLogParams) ([]ListIngestionAuditLogRow, error)
	// Per-device-per-day rows for one site, from the telemetry_daily continuous
	// aggregate. The registry layer sums across a site's devices per day (a
	// site can have more than one device) and falls back to
	// GetRawEnergyReadingsForDeviceDay for any device-day where has_reset is
	// true, rather than trusting energy_end_kwh - energy_start_kwh blindly
	// across a counter reset.
	ListSiteDailyRollup(ctx context.Context, arg ListSiteDailyRollupParams) ([]ListSiteDailyRollupRow, error)
	// Per-site coverage breakdown, keyset-paginated on site_id (simple textual
	// keyset — site_id is already the sites PK, so no secondary tiebreaker is
	// needed the way created_at-sorted lists elsewhere need one).
	ListSiteHealth(ctx context.Context, arg ListSiteHealthParams) ([]ListSiteHealthRow, error)
	// Keyset pagination: pass cursor_created_at/cursor_site_id as NULL for the
	// first page. When restricting to a single site (restricted-role callers),
	// pass site_filter; NULL means "all sites" (operator).
	ListSites(ctx context.Context, arg ListSitesParams) ([]Site, error)
	// Unpaginated site metadata used only as an internal join for
	// benchmarking/trends/comparisons (system size, inverter model, cohort).
	// Not itself an API list endpoint a client paginates — the user-facing
	// pagination is on the computed segments/periods, which stay small and
	// bounded regardless of fleet size at the scale this stack targets today.
	ListSitesForAnalytics(ctx context.Context) ([]ListSitesForAnalyticsRow, error)
	// Keyset pagination on (ts, device_id) DESC. cursor_ts NULL means first page.
	// from_ts/to_ts NULL means unbounded on that side.
	ListTelemetryForSite(ctx context.Context, arg ListTelemetryForSiteParams) ([]ListTelemetryForSiteRow, error)
	// The Phase 3 catch-up on migration 0002's own deferred TODO ("a
	// browsing/reporting UI on this table is Phase 3"). Keyset-paginated on
	// (created_at, id); every filter is optional (NULL = don't filter on it).
	ListUserActionAuditLog(ctx context.Context, arg ListUserActionAuditLogParams) ([]ListUserActionAuditLogRow, error)
	MarkExportJobCompleted(ctx context.Context, arg MarkExportJobCompletedParams) error
	MarkExportJobFailed(ctx context.Context, arg MarkExportJobFailedParams) error
	MarkExportJobRunning(ctx context.Context, id int64) error
	MarkInviteAccepted(ctx context.Context, id int64) error
	MarkPasswordResetTokenUsed(ctx context.Context, id int64) error
	RevokeDevice(ctx context.Context, deviceID string) (Device, error)
	RotateDeviceSecret(ctx context.Context, arg RotateDeviceSecretParams) (Device, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
