// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Forward-only, same as the MQTT ingestor's step 7 — an out-of-order or
	// backfilled reading must never walk this backward.
	AdvanceDeviceLastSeen(ctx context.Context, arg AdvanceDeviceLastSeenParams) error
	CountDevices(ctx context.Context) (int64, error)
	// cutoff is computed in Go from ONLINE_THRESHOLD_MINUTES, never a SQL
	// literal, so the threshold is configurable without a query change.
	// Filters on last_contact_at (reachability), not last_seen_at (reading
	// freshness) — see internal/registry's two-signal online/data_gap model.
	CountOnlineDevices(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	CreateCloudImportToken(ctx context.Context, arg CreateCloudImportTokenParams) (CloudImportToken, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	// Append-only — never UPDATE. Past reports must stay reproducible even if
	// the official factor changes later.
	CreateEmissionFactor(ctx context.Context, arg CreateEmissionFactorParams) (GridEmissionFactor, error)
	CreateExportJob(ctx context.Context, arg CreateExportJobParams) (ExportJob, error)
	// Same "audit first, unconditionally, before any validation" discipline
	// as cmd/ingestor/main.go's raw-pgx insert — used by the cloud-import
	// path so a cloud-pushed reading gets the identical audit trail a real
	// MQTT message does. prev_hash/entry_hash are filled in by
	// trg_ingestion_audit_log_chain (migrations/0013), not here.
	CreateIngestionAuditRow(ctx context.Context, arg CreateIngestionAuditRowParams) (int64, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateSandboxReading(ctx context.Context, arg CreateSandboxReadingParams) error
	CreateSandboxRun(ctx context.Context, arg CreateSandboxRunParams) (SandboxRun, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserActionAuditLog(ctx context.Context, arg CreateUserActionAuditLogParams) error
	// Sum of the most recent power_kw reading per online (not revoked,
	// contacted within the online threshold) device — a live "how much
	// power right now" figure, distinct from any cumulative/historical
	// energy total elsewhere on this platform. A LATERAL join per device,
	// not a rollup — deliberately live, not pre-aggregated.
	CurrentFleetGeneration(ctx context.Context, onlineCutoff pgtype.Timestamptz) (float64, error)
	// Lazy self-cleanup instead of a cron job: run once whenever a new
	// upload happens (see registry.Sandbox.Upload). This is public,
	// unauthenticated, and accumulates over time — nothing else ever purges
	// it otherwise.
	DeleteOldSandboxRuns(ctx context.Context, createdAt pgtype.Timestamptz) error
	// Same optional-cohort-filter pattern as ListFleetDailyRollup — used by
	// Analytics.FleetSpecificYield to normalize fleet-wide energy against
	// fleet-wide (or cohort-wide) capacity, not one site's.
	FleetCapacityForCohort(ctx context.Context, cohortID pgtype.Text) (pgtype.Numeric, error)
	// Ratio-of-sums coverage (sum(actual)/sum(expected) across all devices),
	// not an average of per-device percentages — avoids a brand-new device's
	// tiny expected-readings denominator distorting the fleet-wide figure.
	// Coverage percentage itself is computed in Go from these two sums to
	// avoid a division-by-zero edge case in SQL when there are no devices yet.
	FleetHealthTotals(ctx context.Context, arg FleetHealthTotalsParams) (FleetHealthTotalsRow, error)
	FleetTotals(ctx context.Context) (FleetTotalsRow, error)
	// The most recently effective factor for a country. Returns pgx.ErrNoRows
	// until an operator has explicitly set one — callers must turn that into a
	// 409, never a fabricated default.
	GetCurrentEmissionFactor(ctx context.Context, country string) (GridEmissionFactor, error)
	GetDevice(ctx context.Context, deviceID string) (Device, error)
	// Same lookup cmd/ingestor/main.go runs as raw pgx on the MQTT hot path
	// (AGENTS.md's stack-split rationale doesn't apply here — this serves an
	// infrequent HTTP webhook, not a high-frequency broker subscription) —
	// used by the cloud-import path so both ingestion routes apply the exact
	// same revoked-device check and site-specific plausibility ceiling.
	GetDeviceWithSiteContext(ctx context.Context, deviceID string) (GetDeviceWithSiteContextRow, error)
	// The first operator account ever created in this environment — i.e.
	// the one created via cmd/seed-operator, not necessarily still the only
	// operator. Used to route marketing-site notifications (demo requests)
	// to a real inbox without a dedicated "company notification address"
	// concept in the schema.
	GetEarliestOperator(ctx context.Context) (User, error)
	GetExportJob(ctx context.Context, id int64) (ExportJob, error)
	// Intraday "power right now, over time" curve — raw telemetry bucketed
	// to 5-minute intervals and averaged across every device, optionally
	// scoped to a cohort. Distinct from telemetry_daily (one row per
	// calendar day): this reads the raw hypertable directly since the
	// window is always short (a day or so), so pre-materializing it isn't
	// worth the extra continuous aggregate. Feeds the Dashboard's
	// "Generation Overview" Day view — a real sunrise-to-sunset power
	// curve, not the daily energy totals every other fleet chart plots.
	GetFleetPowerCurve(ctx context.Context, arg GetFleetPowerCurveParams) ([]GetFleetPowerCurveRow, error)
	// Continuous aggregates can't express argmax, so the peak reading's time
	// of day is resolved via a narrow indexed point lookup instead of a scan.
	GetPeakReadingTimeForDeviceDay(ctx context.Context, arg GetPeakReadingTimeForDeviceDayParams) (pgtype.Timestamptz, error)
	GetPrimarySite(ctx context.Context) (Site, error)
	// Reset-day fallback: ordered readings for one device on one day. The
	// registry computes true daily energy as sum(max(0, e[i] - e[i-1])) over
	// consecutive readings — this correctly captures both the pre-reset and
	// post-reset segments' real generation while ignoring the reset's negative
	// delta, without needing to know exactly when in the day the reset
	// occurred.
	GetRawEnergyReadingsForDeviceDay(ctx context.Context, arg GetRawEnergyReadingsForDeviceDayParams) ([]GetRawEnergyReadingsForDeviceDayRow, error)
	GetSandboxRun(ctx context.Context, id string) (SandboxRun, error)
	GetSite(ctx context.Context, siteID string) (Site, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	InsertTelemetryReading(ctx context.Context, arg InsertTelemetryReadingParams) (int64, error)
	// Most recent message the ingestor has seen, fleet-wide, regardless of
	// whether it passed validation — the Dashboard's ingestion-pipeline
	// status widget uses "how long ago was that" as its health signal, not
	// a synthetic uptime percentage this platform has no way to compute.
	LastIngestionReceivedAt(ctx context.Context) (pgtype.Timestamptz, error)
	// Bounded to one device's own tokens (there's realistically at most one
	// active, occasionally two mid-rotation) — verified by hash comparison
	// in Go, same pattern as invites/password-reset tokens, since a token
	// isn't looked up by its plaintext value.
	ListActiveCloudImportTokensForDevice(ctx context.Context, deviceID string) ([]CloudImportToken, error)
	// Small, TTL-bounded result set — see migrations/0007's comment on why
	// token_hash isn't looked up by equality.
	ListActiveInvites(ctx context.Context) ([]Invite, error)
	// Same small, TTL-bounded scan-and-bcrypt-compare pattern as
	// ListActiveInvites — see migrations/0007's comment.
	ListActivePasswordResetTokens(ctx context.Context) ([]PasswordResetToken, error)
	// Unbounded on purpose, unlike ListEmissionFactorHistory above — this
	// feeds per-period historical lookup (Emissions.factorAsOf), which needs
	// every revision ever set for the country, not a capped "recent N" list.
	// Safe to leave unbounded: this table only grows via a rare admin action
	// (Emissions.Set), never per-reading, so it stays tiny for the table's
	// entire lifetime — nothing like telemetry's scale.
	ListAllEmissionFactorsForCountry(ctx context.Context, country string) ([]GridEmissionFactor, error)
	// Distinct cohorts currently in use, with aggregated site count/capacity
	// — cohort_id is a free-text grouping field on sites (no dedicated
	// cohorts table), so this is the closest thing to a "list cohorts"
	// query: derived from what's actually assigned, not a separate managed
	// entity a cohort can exist without ever having a site in it.
	ListCohorts(ctx context.Context) ([]ListCohortsRow, error)
	// site_filter NULL means "all devices" (operator, no ?site_id= filter).
	ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error)
	ListEmissionFactorHistory(ctx context.Context, arg ListEmissionFactorHistoryParams) ([]GridEmissionFactor, error)
	ListExportJobsForUser(ctx context.Context, arg ListExportJobsForUserParams) ([]ExportJob, error)
	// Same shape as ListSiteDailyRollup but fleet-wide, optionally filtered to
	// a cohort. Used by fleet energy/trends/benchmark/anomaly registry logic.
	ListFleetDailyRollup(ctx context.Context, arg ListFleetDailyRollupParams) ([]TelemetryDaily, error)
	// The ingestor's own write-only audit trail (every message received,
	// before validation — see migrations/0001_init.sql), finally given a read
	// path. Kept deliberately separate from user_action_audit_log — this is
	// data-quality/verification evidence, not an admin-action trail (see
	// CLAUDE.md: "don't conflate the two"). Joins devices to resolve site_id
	// for site-scoping (restricted users) and display, since the log itself
	// only stores device_id. A device that's since been deleted still shows
	// its audit rows with site_id NULL rather than disappearing.
	ListIngestionAuditLog(ctx context.Context, arg ListIngestionAuditLogParams) ([]ListIngestionAuditLogRow, error)
	// Latest reading per device that reported status='fault' within the
	// window, one row per device (DISTINCT ON), for the Alerts page. A raw
	// scan over recent telemetry, not a rollup — telemetry_daily doesn't
	// track status, and this is bounded to a short recent window, not the
	// full history CLAUDE.md's "hit roll-ups" rule is about.
	ListRecentFaultReadings(ctx context.Context, since pgtype.Timestamptz) ([]ListRecentFaultReadingsRow, error)
	// Feeds the Alerts page — a revocation is a real, timestamped event
	// worth surfacing there, same as an offline/fault condition.
	ListRecentlyRevokedDevices(ctx context.Context, since pgtype.Timestamptz) ([]Device, error)
	// Unpaginated by design — a run is capped at a small row count
	// (registry.MaxSandboxRows) when uploaded, so this always returns a
	// bounded result, same reasoning as ListSitesForAnalytics.
	ListSandboxReadings(ctx context.Context, runID string) ([]SandboxReading, error)
	// Site->country lookup for fleet-wide emissions, which must resolve each
	// site's own grid factor rather than one global default (see
	// internal/registry/emissions.go FleetEmissions). Unpaginated: this is an
	// internal aggregation input, not a user-facing list, and is bounded by
	// fleet size, not telemetry volume.
	ListSiteCountries(ctx context.Context, cohortID pgtype.Text) ([]ListSiteCountriesRow, error)
	// Per-device-per-day rows for one site, from the telemetry_daily continuous
	// aggregate. The registry layer sums across a site's devices per day (a
	// site can have more than one device) and falls back to
	// GetRawEnergyReadingsForDeviceDay for any device-day where has_reset is
	// true, rather than trusting energy_end_kwh - energy_start_kwh blindly
	// across a counter reset.
	ListSiteDailyRollup(ctx context.Context, arg ListSiteDailyRollupParams) ([]ListSiteDailyRollupRow, error)
	// Per-site coverage breakdown, keyset-paginated on site_id (simple textual
	// keyset — site_id is already the sites PK, so no secondary tiebreaker is
	// needed the way created_at-sorted lists elsewhere need one).
	ListSiteHealth(ctx context.Context, arg ListSiteHealthParams) ([]ListSiteHealthRow, error)
	// Site location + capacity, for fleet-wide Performance Ratio — each site
	// needs its own separate irradiance fetch (unlike the fleet energy
	// rollup, this genuinely can't be answered by one query, since the data
	// comes from an external weather API keyed by lat/lng).
	ListSiteLocations(ctx context.Context, cohortID pgtype.Text) ([]ListSiteLocationsRow, error)
	// Keyset pagination: pass cursor_created_at/cursor_site_id as NULL for the
	// first page. When restricting to a single site (restricted-role callers),
	// pass site_filter; NULL means "all sites" (operator).
	ListSites(ctx context.Context, arg ListSitesParams) ([]Site, error)
	// Unpaginated site metadata used only as an internal join for
	// benchmarking/trends/comparisons (system size, inverter model, cohort).
	// Not itself an API list endpoint a client paginates — the user-facing
	// pagination is on the computed segments/periods, which stay small and
	// bounded regardless of fleet size at the scale this stack targets today.
	ListSitesForAnalytics(ctx context.Context) ([]ListSitesForAnalyticsRow, error)
	// Keyset pagination on (ts, device_id) DESC. cursor_ts NULL means first page.
	// from_ts/to_ts NULL means unbounded on that side.
	ListTelemetryForSite(ctx context.Context, arg ListTelemetryForSiteParams) ([]ListTelemetryForSiteRow, error)
	// The Phase 3 catch-up on migration 0002's own deferred TODO ("a
	// browsing/reporting UI on this table is Phase 3"). Keyset-paginated on
	// (created_at, id); every filter is optional (NULL = don't filter on it).
	ListUserActionAuditLog(ctx context.Context, arg ListUserActionAuditLogParams) ([]ListUserActionAuditLogRow, error)
	// Keyset pagination, same convention as ListSites/ListDevices.
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkCloudImportTokenUsed(ctx context.Context, id int64) error
	MarkExportJobCompleted(ctx context.Context, arg MarkExportJobCompletedParams) error
	MarkExportJobFailed(ctx context.Context, arg MarkExportJobFailedParams) error
	MarkExportJobRunning(ctx context.Context, id int64) error
	MarkIngestionAuditError(ctx context.Context, arg MarkIngestionAuditErrorParams) error
	MarkIngestionAuditProcessed(ctx context.Context, id int64) error
	MarkInviteAccepted(ctx context.Context, id int64) error
	MarkPasswordResetTokenUsed(ctx context.Context, id int64) error
	// Mirrors cmd/ingestor/main.go's previousEnergyByTS — chronological
	// lookup by ts, never by insertion order, so reset detection stays
	// correct under out-of-order/backfilled arrival (see domain.
	// DetectEnergyReset's own comment on why this matters).
	PreviousEnergyBeforeTS(ctx context.Context, arg PreviousEnergyBeforeTSParams) (float64, error)
	// Issuing a new token revokes any previous one for the same device — one
	// active credential at a time, same model as device secret rotation.
	RevokeCloudImportTokensForDevice(ctx context.Context, deviceID string) error
	RevokeDevice(ctx context.Context, deviceID string) (Device, error)
	RotateDeviceSecret(ctx context.Context, arg RotateDeviceSecretParams) (Device, error)
	SetSitePrimary(ctx context.Context, siteID string) (Site, error)
	// disabled_at itself, not a boolean flag — NULL means active, a real
	// timestamp means disabled since that moment (audit-friendly, matches
	// devices.revoked_at's existing convention in this codebase).
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (User, error)
	// Paired with SetSitePrimary below (run first, in the same registry
	// method) — the unique index (migrations/0011_primary_site.sql) is the
	// real backstop guaranteeing at most one primary site even without an
	// explicit transaction wrapping both statements.
	UnsetAllPrimarySites(ctx context.Context) error
	// Unconditional reachability signal, same as the MQTT ingestor's step 2 —
	// "we heard from this device at all," independent of whether any of its
	// readings turned out to be valid. Used by the cloud-import path so a
	// cloud-linked device's online/offline status is derived the same way
	// an MQTT device's is.
	UpdateDeviceLastContact(ctx context.Context, arg UpdateDeviceLastContactParams) (Device, error)
	// Corrects a site's country after creation — needed because the
	// migration backfilling this column had to guess 'NG' for every
	// pre-existing row (see migrations/0010_site_country.sql).
	UpdateSiteCountry(ctx context.Context, arg UpdateSiteCountryParams) (Site, error)
	// Corrects/sets a site's GPS coordinates after creation — needed for
	// any site created without them (e.g. cloud-imported sites, where the
	// precise lat/lng only becomes available from a later, more detailed
	// vendor API call than the one used at registration time).
	UpdateSiteLocation(ctx context.Context, arg UpdateSiteLocationParams) (Site, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Recomputes each row's expected hash using the exact same expression as
	// the ingestion_audit_log_chain() trigger (migrations/0013) and compares
	// against what's actually stored — done entirely in SQL so the digest()
	// call here is byte-for-byte the same one that wrote the hash, avoiding
	// any cross-language JSON/text canonicalization mismatch a Go-side
	// recompute would risk. lag() over id order gives each row's expected
	// prev_hash without a second table scan.
	VerifyIngestionAuditChain(ctx context.Context) (VerifyIngestionAuditChainRow, error)
	// Same approach as VerifyIngestionAuditChain, against
	// user_action_audit_log_chain()'s expression instead.
	VerifyUserActionAuditChain(ctx context.Context) (VerifyUserActionAuditChainRow, error)
}

var _ Querier = (*Queries)(nil)
