// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sandbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSandboxReading = `-- name: CreateSandboxReading :exec
INSERT INTO sandbox_readings
    (run_id, row_number, ts, power_kw, energy_kwh_total, voltage_v, status, accepted, rejection_reason, provenance, is_reset, rssi)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateSandboxReadingParams struct {
	RunID           string
	RowNumber       int32
	Ts              pgtype.Timestamptz
	PowerKw         pgtype.Float8
	EnergyKwhTotal  pgtype.Float8
	VoltageV        pgtype.Float8
	Status          pgtype.Text
	Accepted        bool
	RejectionReason pgtype.Text
	Provenance      pgtype.Text
	IsReset         bool
	Rssi            pgtype.Int4
}

func (q *Queries) CreateSandboxReading(ctx context.Context, arg CreateSandboxReadingParams) error {
	_, err := q.db.Exec(ctx, createSandboxReading,
		arg.RunID,
		arg.RowNumber,
		arg.Ts,
		arg.PowerKw,
		arg.EnergyKwhTotal,
		arg.VoltageV,
		arg.Status,
		arg.Accepted,
		arg.RejectionReason,
		arg.Provenance,
		arg.IsReset,
		arg.Rssi,
	)
	return err
}

const createSandboxRun = `-- name: CreateSandboxRun :one
INSERT INTO sandbox_runs (id, system_size_kw, row_count, accepted_count, rejected_count)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, system_size_kw, row_count, accepted_count, rejected_count, created_at
`

type CreateSandboxRunParams struct {
	ID            string
	SystemSizeKw  pgtype.Numeric
	RowCount      int32
	AcceptedCount int32
	RejectedCount int32
}

func (q *Queries) CreateSandboxRun(ctx context.Context, arg CreateSandboxRunParams) (SandboxRun, error) {
	row := q.db.QueryRow(ctx, createSandboxRun,
		arg.ID,
		arg.SystemSizeKw,
		arg.RowCount,
		arg.AcceptedCount,
		arg.RejectedCount,
	)
	var i SandboxRun
	err := row.Scan(
		&i.ID,
		&i.SystemSizeKw,
		&i.RowCount,
		&i.AcceptedCount,
		&i.RejectedCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldSandboxRuns = `-- name: DeleteOldSandboxRuns :exec
DELETE FROM sandbox_runs WHERE created_at < $1
`

// Lazy self-cleanup instead of a cron job: run once whenever a new
// upload happens (see registry.Sandbox.Upload). This is public,
// unauthenticated, and accumulates over time — nothing else ever purges
// it otherwise.
func (q *Queries) DeleteOldSandboxRuns(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldSandboxRuns, createdAt)
	return err
}

const getSandboxRun = `-- name: GetSandboxRun :one
SELECT id, system_size_kw, row_count, accepted_count, rejected_count, created_at FROM sandbox_runs WHERE id = $1
`

func (q *Queries) GetSandboxRun(ctx context.Context, id string) (SandboxRun, error) {
	row := q.db.QueryRow(ctx, getSandboxRun, id)
	var i SandboxRun
	err := row.Scan(
		&i.ID,
		&i.SystemSizeKw,
		&i.RowCount,
		&i.AcceptedCount,
		&i.RejectedCount,
		&i.CreatedAt,
	)
	return i, err
}

const listSandboxReadings = `-- name: ListSandboxReadings :many
SELECT id, run_id, row_number, ts, power_kw, energy_kwh_total, voltage_v, status, accepted, rejection_reason, provenance, is_reset, rssi FROM sandbox_readings WHERE run_id = $1 ORDER BY row_number
`

// Unpaginated by design — a run is capped at a small row count
// (registry.MaxSandboxRows) when uploaded, so this always returns a
// bounded result, same reasoning as ListSitesForAnalytics.
func (q *Queries) ListSandboxReadings(ctx context.Context, runID string) ([]SandboxReading, error) {
	rows, err := q.db.Query(ctx, listSandboxReadings, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SandboxReading
	for rows.Next() {
		var i SandboxReading
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RowNumber,
			&i.Ts,
			&i.PowerKw,
			&i.EnergyKwhTotal,
			&i.VoltageV,
			&i.Status,
			&i.Accepted,
			&i.RejectionReason,
			&i.Provenance,
			&i.IsReset,
			&i.Rssi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
