// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (site_id, name, address, gps_lat, gps_lng, inverter_make_model, system_size_kw, install_date, timezone, cohort_id, country)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING site_id, cohort_id, address, name, gps_lat, gps_lng, inverter_make_model, system_size_kw, install_date, timezone, country, created_at
`

type CreateSiteParams struct {
	SiteID            string
	Name              pgtype.Text
	Address           pgtype.Text
	GpsLat            pgtype.Float8
	GpsLng            pgtype.Float8
	InverterMakeModel pgtype.Text
	SystemSizeKw      pgtype.Numeric
	InstallDate       pgtype.Date
	Timezone          string
	CohortID          pgtype.Text
	Country           string
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.SiteID,
		arg.Name,
		arg.Address,
		arg.GpsLat,
		arg.GpsLng,
		arg.InverterMakeModel,
		arg.SystemSizeKw,
		arg.InstallDate,
		arg.Timezone,
		arg.CohortID,
		arg.Country,
	)
	var i Site
	err := row.Scan(
		&i.SiteID,
		&i.CohortID,
		&i.Address,
		&i.Name,
		&i.GpsLat,
		&i.GpsLng,
		&i.InverterMakeModel,
		&i.SystemSizeKw,
		&i.InstallDate,
		&i.Timezone,
		&i.Country,
		&i.CreatedAt,
	)
	return i, err
}

const fleetTotals = `-- name: FleetTotals :one
SELECT
    count(*)::bigint AS total_sites,
    coalesce(sum(system_size_kw), 0)::numeric AS total_capacity_kw
FROM sites
`

type FleetTotalsRow struct {
	TotalSites      int64
	TotalCapacityKw pgtype.Numeric
}

func (q *Queries) FleetTotals(ctx context.Context) (FleetTotalsRow, error) {
	row := q.db.QueryRow(ctx, fleetTotals)
	var i FleetTotalsRow
	err := row.Scan(&i.TotalSites, &i.TotalCapacityKw)
	return i, err
}

const getSite = `-- name: GetSite :one
SELECT site_id, cohort_id, address, name, gps_lat, gps_lng, inverter_make_model, system_size_kw, install_date, timezone, country, created_at FROM sites WHERE site_id = $1
`

func (q *Queries) GetSite(ctx context.Context, siteID string) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, siteID)
	var i Site
	err := row.Scan(
		&i.SiteID,
		&i.CohortID,
		&i.Address,
		&i.Name,
		&i.GpsLat,
		&i.GpsLng,
		&i.InverterMakeModel,
		&i.SystemSizeKw,
		&i.InstallDate,
		&i.Timezone,
		&i.Country,
		&i.CreatedAt,
	)
	return i, err
}

const listSiteCountries = `-- name: ListSiteCountries :many
SELECT site_id, country FROM sites
WHERE $1::text IS NULL OR cohort_id = $1
`

type ListSiteCountriesRow struct {
	SiteID  string
	Country string
}

// Site->country lookup for fleet-wide emissions, which must resolve each
// site's own grid factor rather than one global default (see
// internal/registry/emissions.go FleetEmissions). Unpaginated: this is an
// internal aggregation input, not a user-facing list, and is bounded by
// fleet size, not telemetry volume.
func (q *Queries) ListSiteCountries(ctx context.Context, cohortID pgtype.Text) ([]ListSiteCountriesRow, error) {
	rows, err := q.db.Query(ctx, listSiteCountries, cohortID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSiteCountriesRow
	for rows.Next() {
		var i ListSiteCountriesRow
		if err := rows.Scan(&i.SiteID, &i.Country); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSites = `-- name: ListSites :many
SELECT site_id, cohort_id, address, name, gps_lat, gps_lng, inverter_make_model, system_size_kw, install_date, timezone, country, created_at FROM sites
WHERE ($1::text IS NULL OR site_id = $1)
  AND (
    $2::timestamptz IS NULL
    OR (created_at, site_id) < ($2::timestamptz, $3::text)
  )
ORDER BY created_at DESC, site_id DESC
LIMIT $4
`

type ListSitesParams struct {
	SiteFilter      pgtype.Text
	CursorCreatedAt pgtype.Timestamptz
	CursorSiteID    pgtype.Text
	PageLimit       int32
}

// Keyset pagination: pass cursor_created_at/cursor_site_id as NULL for the
// first page. When restricting to a single site (restricted-role callers),
// pass site_filter; NULL means "all sites" (operator).
func (q *Queries) ListSites(ctx context.Context, arg ListSitesParams) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSites,
		arg.SiteFilter,
		arg.CursorCreatedAt,
		arg.CursorSiteID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.SiteID,
			&i.CohortID,
			&i.Address,
			&i.Name,
			&i.GpsLat,
			&i.GpsLng,
			&i.InverterMakeModel,
			&i.SystemSizeKw,
			&i.InstallDate,
			&i.Timezone,
			&i.Country,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteCountry = `-- name: UpdateSiteCountry :one
UPDATE sites SET country = $2 WHERE site_id = $1
RETURNING site_id, cohort_id, address, name, gps_lat, gps_lng, inverter_make_model, system_size_kw, install_date, timezone, country, created_at
`

type UpdateSiteCountryParams struct {
	SiteID  string
	Country string
}

// Corrects a site's country after creation — needed because the
// migration backfilling this column had to guess 'NG' for every
// pre-existing row (see migrations/0010_site_country.sql).
func (q *Queries) UpdateSiteCountry(ctx context.Context, arg UpdateSiteCountryParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSiteCountry, arg.SiteID, arg.Country)
	var i Site
	err := row.Scan(
		&i.SiteID,
		&i.CohortID,
		&i.Address,
		&i.Name,
		&i.GpsLat,
		&i.GpsLng,
		&i.InverterMakeModel,
		&i.SystemSizeKw,
		&i.InstallDate,
		&i.Timezone,
		&i.Country,
		&i.CreatedAt,
	)
	return i, err
}
