// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTelemetryForSite = `-- name: ListTelemetryForSite :many
SELECT ts, power_kw, energy_kwh_total, voltage_v, status, device_id
FROM telemetry
WHERE site_id = $1
  AND ($2::timestamptz IS NULL OR ts >= $2)
  AND ($3::timestamptz IS NULL OR ts <= $3)
  AND (
    $4::timestamptz IS NULL
    OR (ts, device_id) < ($4::timestamptz, $5::text)
  )
ORDER BY ts DESC, device_id DESC
LIMIT $6
`

type ListTelemetryForSiteParams struct {
	SiteID         string
	FromTs         pgtype.Timestamptz
	ToTs           pgtype.Timestamptz
	CursorTs       pgtype.Timestamptz
	CursorDeviceID pgtype.Text
	PageLimit      int32
}

type ListTelemetryForSiteRow struct {
	Ts             pgtype.Timestamptz
	PowerKw        float64
	EnergyKwhTotal float64
	VoltageV       pgtype.Float8
	Status         ReadingStatus
	DeviceID       string
}

// Keyset pagination on (ts, device_id) DESC. cursor_ts NULL means first page.
// from_ts/to_ts NULL means unbounded on that side.
func (q *Queries) ListTelemetryForSite(ctx context.Context, arg ListTelemetryForSiteParams) ([]ListTelemetryForSiteRow, error) {
	rows, err := q.db.Query(ctx, listTelemetryForSite,
		arg.SiteID,
		arg.FromTs,
		arg.ToTs,
		arg.CursorTs,
		arg.CursorDeviceID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTelemetryForSiteRow
	for rows.Next() {
		var i ListTelemetryForSiteRow
		if err := rows.Scan(
			&i.Ts,
			&i.PowerKw,
			&i.EnergyKwhTotal,
			&i.VoltageV,
			&i.Status,
			&i.DeviceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
