// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeviceWithSiteContext = `-- name: GetDeviceWithSiteContext :one
SELECT d.site_id, d.revoked_at, s.system_size_kw, s.timezone
FROM devices d JOIN sites s ON s.site_id = d.site_id
WHERE d.device_id = $1
`

type GetDeviceWithSiteContextRow struct {
	SiteID       pgtype.Text
	RevokedAt    pgtype.Timestamptz
	SystemSizeKw pgtype.Numeric
	Timezone     string
}

// Same lookup cmd/ingestor/main.go runs as raw pgx on the MQTT hot path
// (AGENTS.md's stack-split rationale doesn't apply here — this serves an
// infrequent HTTP webhook, not a high-frequency broker subscription) —
// used by the cloud-import path so both ingestion routes apply the exact
// same revoked-device check and site-specific plausibility ceiling.
func (q *Queries) GetDeviceWithSiteContext(ctx context.Context, deviceID string) (GetDeviceWithSiteContextRow, error) {
	row := q.db.QueryRow(ctx, getDeviceWithSiteContext, deviceID)
	var i GetDeviceWithSiteContextRow
	err := row.Scan(
		&i.SiteID,
		&i.RevokedAt,
		&i.SystemSizeKw,
		&i.Timezone,
	)
	return i, err
}

const insertTelemetryReading = `-- name: InsertTelemetryReading :execrows
INSERT INTO telemetry (
    device_id, site_id, ts, power_kw, energy_kwh_total, voltage_v, status, provenance, quality_flags, rssi,
    pv_power_kw, battery_soc_pct, battery_voltage_v, pv_voltage_v, output_voltage_v, load_power_kw, grid_power_kw
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
ON CONFLICT (device_id, ts) DO NOTHING
`

type InsertTelemetryReadingParams struct {
	DeviceID        string
	SiteID          string
	Ts              pgtype.Timestamptz
	PowerKw         float64
	EnergyKwhTotal  float64
	VoltageV        pgtype.Float8
	Status          ReadingStatus
	Provenance      ProvenanceType
	QualityFlags    []string
	Rssi            pgtype.Int4
	PvPowerKw       pgtype.Float8
	BatterySocPct   pgtype.Int2
	BatteryVoltageV pgtype.Float8
	PvVoltageV      pgtype.Float8
	OutputVoltageV  pgtype.Float8
	LoadPowerKw     pgtype.Float8
	GridPowerKw     pgtype.Float8
}

func (q *Queries) InsertTelemetryReading(ctx context.Context, arg InsertTelemetryReadingParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTelemetryReading,
		arg.DeviceID,
		arg.SiteID,
		arg.Ts,
		arg.PowerKw,
		arg.EnergyKwhTotal,
		arg.VoltageV,
		arg.Status,
		arg.Provenance,
		arg.QualityFlags,
		arg.Rssi,
		arg.PvPowerKw,
		arg.BatterySocPct,
		arg.BatteryVoltageV,
		arg.PvVoltageV,
		arg.OutputVoltageV,
		arg.LoadPowerKw,
		arg.GridPowerKw,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTelemetryForSite = `-- name: ListTelemetryForSite :many
SELECT ts, power_kw, energy_kwh_total, voltage_v, status, device_id, rssi,
       pv_power_kw, battery_soc_pct, battery_voltage_v, pv_voltage_v, output_voltage_v, load_power_kw, grid_power_kw
FROM telemetry
WHERE site_id = $1
  AND ($2::timestamptz IS NULL OR ts >= $2)
  AND ($3::timestamptz IS NULL OR ts <= $3)
  AND (
    $4::timestamptz IS NULL
    OR (ts, device_id) < ($4::timestamptz, $5::text)
  )
ORDER BY ts DESC, device_id DESC
LIMIT $6
`

type ListTelemetryForSiteParams struct {
	SiteID         string
	FromTs         pgtype.Timestamptz
	ToTs           pgtype.Timestamptz
	CursorTs       pgtype.Timestamptz
	CursorDeviceID pgtype.Text
	PageLimit      int32
}

type ListTelemetryForSiteRow struct {
	Ts              pgtype.Timestamptz
	PowerKw         float64
	EnergyKwhTotal  float64
	VoltageV        pgtype.Float8
	Status          ReadingStatus
	DeviceID        string
	Rssi            pgtype.Int4
	PvPowerKw       pgtype.Float8
	BatterySocPct   pgtype.Int2
	BatteryVoltageV pgtype.Float8
	PvVoltageV      pgtype.Float8
	OutputVoltageV  pgtype.Float8
	LoadPowerKw     pgtype.Float8
	GridPowerKw     pgtype.Float8
}

// Keyset pagination on (ts, device_id) DESC. cursor_ts NULL means first page.
// from_ts/to_ts NULL means unbounded on that side.
func (q *Queries) ListTelemetryForSite(ctx context.Context, arg ListTelemetryForSiteParams) ([]ListTelemetryForSiteRow, error) {
	rows, err := q.db.Query(ctx, listTelemetryForSite,
		arg.SiteID,
		arg.FromTs,
		arg.ToTs,
		arg.CursorTs,
		arg.CursorDeviceID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTelemetryForSiteRow
	for rows.Next() {
		var i ListTelemetryForSiteRow
		if err := rows.Scan(
			&i.Ts,
			&i.PowerKw,
			&i.EnergyKwhTotal,
			&i.VoltageV,
			&i.Status,
			&i.DeviceID,
			&i.Rssi,
			&i.PvPowerKw,
			&i.BatterySocPct,
			&i.BatteryVoltageV,
			&i.PvVoltageV,
			&i.OutputVoltageV,
			&i.LoadPowerKw,
			&i.GridPowerKw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const previousEnergyBeforeTS = `-- name: PreviousEnergyBeforeTS :one
SELECT energy_kwh_total FROM telemetry WHERE device_id = $1 AND ts < $2 ORDER BY ts DESC LIMIT 1
`

type PreviousEnergyBeforeTSParams struct {
	DeviceID string
	Ts       pgtype.Timestamptz
}

// Mirrors cmd/ingestor/main.go's previousEnergyByTS — chronological
// lookup by ts, never by insertion order, so reset detection stays
// correct under out-of-order/backfilled arrival (see domain.
// DetectEnergyReset's own comment on why this matters).
func (q *Queries) PreviousEnergyBeforeTS(ctx context.Context, arg PreviousEnergyBeforeTSParams) (float64, error) {
	row := q.db.QueryRow(ctx, previousEnergyBeforeTS, arg.DeviceID, arg.Ts)
	var energy_kwh_total float64
	err := row.Scan(&energy_kwh_total)
	return energy_kwh_total, err
}
