// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, site_id)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, role, site_id, created_at, disabled_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Role         UserRole
	SiteID       pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.SiteID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.SiteID,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const createUserActionAuditLog = `-- name: CreateUserActionAuditLog :exec
INSERT INTO user_action_audit_log (actor_user_id, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserActionAuditLogParams struct {
	ActorUserID pgtype.Int8
	Action      string
	TargetType  pgtype.Text
	TargetID    pgtype.Text
	Metadata    []byte
}

func (q *Queries) CreateUserActionAuditLog(ctx context.Context, arg CreateUserActionAuditLogParams) error {
	_, err := q.db.Exec(ctx, createUserActionAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, site_id, created_at, disabled_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.SiteID,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, site_id, created_at, disabled_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.SiteID,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}
