// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, site_id)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, role, site_id, created_at, disabled_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Role         UserRole
	SiteID       pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.SiteID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.SiteID,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const createUserActionAuditLog = `-- name: CreateUserActionAuditLog :exec
INSERT INTO user_action_audit_log (actor_user_id, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserActionAuditLogParams struct {
	ActorUserID pgtype.Int8
	Action      string
	TargetType  pgtype.Text
	TargetID    pgtype.Text
	Metadata    []byte
}

func (q *Queries) CreateUserActionAuditLog(ctx context.Context, arg CreateUserActionAuditLogParams) error {
	_, err := q.db.Exec(ctx, createUserActionAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	return err
}

const getEarliestOperator = `-- name: GetEarliestOperator :one
SELECT id, email, password_hash, role, site_id, created_at, disabled_at FROM users WHERE role = 'operator' ORDER BY created_at ASC, id ASC LIMIT 1
`

// The first operator account ever created in this environment — i.e.
// the one created via cmd/seed-operator, not necessarily still the only
// operator. Used to route marketing-site notifications (demo requests)
// to a real inbox without a dedicated "company notification address"
// concept in the schema.
func (q *Queries) GetEarliestOperator(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, getEarliestOperator)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.SiteID,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, site_id, created_at, disabled_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.SiteID,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, site_id, created_at, disabled_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.SiteID,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, role, site_id, created_at, disabled_at FROM users
WHERE (
    $1::timestamptz IS NULL
    OR (created_at, id) < ($1::timestamptz, $2::bigint)
)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListUsersParams struct {
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.Int8
	PageLimit       int32
}

// Keyset pagination, same convention as ListSites/ListDevices.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.CursorCreatedAt, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.SiteID,
			&i.CreatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDisabled = `-- name: SetUserDisabled :one
UPDATE users SET disabled_at = $2 WHERE id = $1
RETURNING id, email, password_hash, role, site_id, created_at, disabled_at
`

type SetUserDisabledParams struct {
	ID         int64
	DisabledAt pgtype.Timestamptz
}

// disabled_at itself, not a boolean flag — NULL means active, a real
// timestamp means disabled since that moment (audit-friendly, matches
// devices.revoked_at's existing convention in this codebase).
func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserDisabled, arg.ID, arg.DisabledAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.SiteID,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}
