// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendor_connections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVendorConnection = `-- name: CreateVendorConnection :one
INSERT INTO vendor_connections (site_id, provider, encrypted_credential, created_by_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, site_id, provider, external_ref, status, last_synced_at, last_error, created_at
`

type CreateVendorConnectionParams struct {
	SiteID              string
	Provider            string
	EncryptedCredential []byte
	CreatedByUserID     pgtype.Int8
}

type CreateVendorConnectionRow struct {
	ID           int64
	SiteID       string
	Provider     string
	ExternalRef  pgtype.Text
	Status       string
	LastSyncedAt pgtype.Timestamptz
	LastError    pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateVendorConnection(ctx context.Context, arg CreateVendorConnectionParams) (CreateVendorConnectionRow, error) {
	row := q.db.QueryRow(ctx, createVendorConnection,
		arg.SiteID,
		arg.Provider,
		arg.EncryptedCredential,
		arg.CreatedByUserID,
	)
	var i CreateVendorConnectionRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Provider,
		&i.ExternalRef,
		&i.Status,
		&i.LastSyncedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getVendorConnectionCredential = `-- name: GetVendorConnectionCredential :one
SELECT encrypted_credential FROM vendor_connections WHERE id = $1
`

// Decryption happens in Go (internal/registry/vendor_connections.go) —
// this just returns the ciphertext, never anything already decrypted.
func (q *Queries) GetVendorConnectionCredential(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getVendorConnectionCredential, id)
	var encrypted_credential []byte
	err := row.Scan(&encrypted_credential)
	return encrypted_credential, err
}

const listActiveVendorConnections = `-- name: ListActiveVendorConnections :many
SELECT id, site_id, provider, encrypted_credential, external_ref, last_synced_at
FROM vendor_connections
WHERE status IN ('pending', 'active', 'error')
ORDER BY id
`

type ListActiveVendorConnectionsRow struct {
	ID                  int64
	SiteID              string
	Provider            string
	EncryptedCredential []byte
	ExternalRef         pgtype.Text
	LastSyncedAt        pgtype.Timestamptz
}

// Feeds cmd/vendor-sync's poll loop — every connection the sync binary
// should still be trying, across every customer: 'pending' (never
// synced yet — MarkVendorConnectionSynced is what promotes a row to
// 'active', so pending has to be included here or a brand-new
// connection could never reach 'active' in the first place), 'active',
// and 'error' (retried every cycle rather than given up on — a vendor
// outage or a momentarily wrong password shouldn't need a customer to
// reconnect by hand). Only 'revoked' is excluded — the customer's own
// explicit stop signal.
func (q *Queries) ListActiveVendorConnections(ctx context.Context) ([]ListActiveVendorConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveVendorConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveVendorConnectionsRow
	for rows.Next() {
		var i ListActiveVendorConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Provider,
			&i.EncryptedCredential,
			&i.ExternalRef,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorConnectionsForSite = `-- name: ListVendorConnectionsForSite :many
SELECT id, site_id, provider, external_ref, status, last_synced_at, last_error, created_at
FROM vendor_connections
WHERE site_id = $1
ORDER BY created_at DESC
`

type ListVendorConnectionsForSiteRow struct {
	ID           int64
	SiteID       string
	Provider     string
	ExternalRef  pgtype.Text
	Status       string
	LastSyncedAt pgtype.Timestamptz
	LastError    pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListVendorConnectionsForSite(ctx context.Context, siteID string) ([]ListVendorConnectionsForSiteRow, error) {
	rows, err := q.db.Query(ctx, listVendorConnectionsForSite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVendorConnectionsForSiteRow
	for rows.Next() {
		var i ListVendorConnectionsForSiteRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Provider,
			&i.ExternalRef,
			&i.Status,
			&i.LastSyncedAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVendorConnectionError = `-- name: MarkVendorConnectionError :exec
UPDATE vendor_connections SET status = 'error', last_error = $2 WHERE id = $1
`

type MarkVendorConnectionErrorParams struct {
	ID        int64
	LastError pgtype.Text
}

// A provider-level failure marks only this one connection degraded —
// never touches devices.last_contact_at (device-offline) or any other
// customer's own connection row. See internal/syncengine's isolation
// requirement.
func (q *Queries) MarkVendorConnectionError(ctx context.Context, arg MarkVendorConnectionErrorParams) error {
	_, err := q.db.Exec(ctx, markVendorConnectionError, arg.ID, arg.LastError)
	return err
}

const markVendorConnectionSynced = `-- name: MarkVendorConnectionSynced :exec
UPDATE vendor_connections
SET status = 'active', last_synced_at = $2, last_error = NULL, external_ref = coalesce($3, external_ref)
WHERE id = $1
`

type MarkVendorConnectionSyncedParams struct {
	ID           int64
	LastSyncedAt pgtype.Timestamptz
	ExternalRef  pgtype.Text
}

func (q *Queries) MarkVendorConnectionSynced(ctx context.Context, arg MarkVendorConnectionSyncedParams) error {
	_, err := q.db.Exec(ctx, markVendorConnectionSynced, arg.ID, arg.LastSyncedAt, arg.ExternalRef)
	return err
}

const revokeVendorConnection = `-- name: RevokeVendorConnection :exec
UPDATE vendor_connections SET status = 'revoked' WHERE id = $1 AND site_id = $2
`

type RevokeVendorConnectionParams struct {
	ID     int64
	SiteID string
}

func (q *Queries) RevokeVendorConnection(ctx context.Context, arg RevokeVendorConnectionParams) error {
	_, err := q.db.Exec(ctx, revokeVendorConnection, arg.ID, arg.SiteID)
	return err
}
